{%set name = "girder-client" %}
{%set version = "2.0.0" %}
{%set hash_type = "sha256" %}
{%set hash_val = "5724050e044b1d06093c22e6a004c7b8a074739e6fc0a7bb6cdf33a55beaeec4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  entry_points:
    - girder-cli = girder_client.cli:main

  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - diskcache
    - requests >=2.4.2
    - six

test:
  imports:
    - girder_client

  commands:
    - girder-cli --help

about:
  home: http://girder.readthedocs.org/en/latest/python-client.html
  license: Apache 2.0
  license_family: Apache
  summary: 'Python client for interacting with Girder servers'
  doc_url: http://girder.readthedocs.org/en/latest/python-client.html
  dev_url: https://github.com/girder/girder/tree/master/clients/python

extra:
  recipe-maintainers:
    - pmlandwehr
