travis:
  secure:
    BINSTAR_TOKEN: yIC8mjJVBLZxtSHnVM1a8LCMLWwNB/K4H2N7iaHoEP7NgXEjnIktXDbrg/PR0LEplwVZOjMkmzwDQR73gCipvKiHhJ5vJ4rDclx6z7Mg8lCxbSrR2XB4IidZTwk0XDG85tneUJMdtbuOe/ddKpO8qtuGrHkprNj6lf3F7zc4ADoojK0YllvGSIwafFiUhtMeJVrcar7PgwxZfhLS1o4og7D+HXjiKUgyt5rA+zpJiHqZwKgWfp2OtFMPq9UUzKr3Rnfyxn6nL/HZkk3kIiVBhY3nYJc4CG/1MntxIXUITEPnPUpuGzrNVA1DkeHRqhx9ioJFd8m83Gx9oHXRCBpAM4mZOUUCdUAOzmoLEGHm2nRr9Tx7d+P4TO8p3FHkAzxXAOvIu3mDR0ZcVWFVgdanZgX8PfIZud9nQLsVGEvEhXGSRLUJuxFTyVGTvf92Wo/SZh06ZWf5Czy7KcKMuG+VP+yMHB5x1gFoQAJPdqnlWrXL5iIwbpUPO8WqZFRcnPGToHgv2DO9Pgz+cThTwK+b8vemw7P143SyKxDk4IIJlZ7gIiT5uuZU9Z1aYyvEup5v2ibaekDEoGAHNhpiBKaq0dTX15iPt5hkah8kaYhs3APehhTeyF9aJV0Up+hjQBzKl7MekhuapoRK9IwFwXEZu2k51M3p7wsFLGzqkn3VME8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
