travis:
  secure:
    BINSTAR_TOKEN: GtmeA1lwBFftFseNYDsqmhle4Prip3+M+SqiRvagTHlNjCGtBYyKR6nmaM8S+8dmpg3RolIcj5Svt3/b0u+yGC9UxKGj0fX4iurcTVDucR4C10eqUUqkG9WL6HCA9+b23W4WLr6EXTAc3WZohFOPA+4MN5OG+jHt1koU4v5lSdDy50iMqPcJhuqotabMItqzC9pd/w30hk/UCDkic4X51NMIGyRYZE3JSJLFGNZoEI/Ox92AcHehCz2LgaI7ONlg8uNCftEl0yW12ougt9WvVp9teHDCn7ZqFA0J0bUIDB106QjoUIn3j6mcBE9/vZKROLltbmHRK2GlvRYDOTBYu0s9cVhbjjVC+7qICkZRQNaunueYit2I0a9VN7TlT+7dwaJ49tjihLjcz5Rmag8w3kA35OWK006cVjNjz4NfVmvHZUTQtTW4Eq2F6np8Vrd1UyxoUoKzGKhGt+Z0GvxoMm7zcbEoyGzQxisztIecElJTF1LsF9hfS9APauSlIeibkj9+gp26rEs7nowjnUUth4BhbDy7y8hZkoG/qoVI1qAfwi+T9A2ZuJKf4WO2R+3pEN8fPaIwdrlsfxycpsXuxNSFKlUlMa2XYSRk9eF0EFrF7SY8ZD60SrQEg1f96hRj+fE/4bKuEoOLJcWLglflE3+KmmZExePN91tw4uEbqc4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
