travis:
  secure:
    BINSTAR_TOKEN: VAI0z8zSQERM80UeZGFOH3MMZDSxljNeEwY9Q4kM8CgWjRywvE03JYzBAVTR5/WQrOOXVmL0+KbWX8+cHJSE0PawUTXzRsJR0NyIjjKe4AZ/VkDHtJ33h4g4moMKL9EnYZn4Ot7Nws825NdZT9+ifoHj/zyP/gHgYOdWiSucHeKldw+yiHCxx2LUWg1/Fm4grJZ3k24JQxrDGYVhSQUb0ZOA1Kwrus6N6+jsIhvc3xYOAsxqCSa0N2jJmhKTAiecwmedXJ0gbEWKBHB4dgmfRLqzbcQy7Y7b/NWEVn9TlQUwjiW89rZVbW+wvImFaOVjw0diA29rsGfUqGq+x+xAA+JBzKR+FbUaS+tK1C/i6vWTkUBZ+aZyEtHWOKz+9HHyzZpjJN3khf1IWwU32NyiUX1IasZB3X7HMTVvzzaQLJj+M5TXhMKfzryvwwk+fwmACuj1gS+B6ekcjv+0exU+VTWwartxATqxpoTbUHeWz5FGNeKqhQjL+p1AR94AnJEd4rwlYbBEbEmnDUBb6+Qy1ACmMK4WWwNa+v9Bs8ksg7w/aMSOqTUIl3GZKm3QcreC4qMAbN9ej2lHc+ITUpXphwxPmVK44Gd8gJ8u3JDhdYUgJYYD5yBjuiGRMa77hVPlZ5BevAmyfZrkuxqwCPSSZXVdLs+FX4HSbMK+qgoTPl4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
