travis:
  secure:
    BINSTAR_TOKEN: QZtMpfz037/oURWU/R5g0+L1ZcWtGmt5Soaz8FMOhYMKXRvgEjyg5s43pEP9LI9Ckwgbyu49yp4roztLPOxilLCZeYfDMqKa3ruYVZv47l6/a4DllAwA1+lBSxPHyxs/qjbWNUDUTBLPKalIxtPjSjtJsGQfArwNnpD/G7qJgm3ecE+zAXUi0P+mX4b9rU5wXVt9Co4vpKyDhbvnN5KF1MM6Q01bfcGLNrenjGplIyL7PD/FTQKmRWXl0RnWBW6iRPyxQ4MEzvudWOrmku55YbWSkHOfh+QCbo587OE0X+U0QTe31/nxiFN8X1X7FHme1AmnMS1aHaB32ezfcld4pVS7I9qY5yFDKeMxIMlmfIqEunpGqOGq8ZzTfD3gGB2MKzumWWn0wMtGNLr0cKdowZxxOIKztQVjYi5dA8o8ybxyJMbVh4nhpWKF3LqsPreKM4rStZ+12izZ9CS0P7E1pgiQ1O0LQah1/wZRIb/fXLZM+kNkVnsUNZMGxnZTldRrFDEarMcCoQpvHrHtM/Kxw5ae/e/UOqLEE2njUFfvQ4NHNXLR1woAx1ypeqaT0nR3D9CVlT5xYQMOrOeFQeoHxR/WwAGILlK4JFtEN1ekcF+8RRUe7LARRM8EMnaGqlTbYJ2bF5Beczt2GX7GlPGaaxgyXG+SKdtLNeywPEPHw4w=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
