travis:
  secure:
    BINSTAR_TOKEN: EP9K+hgGhGplduAohjv/HGcr17gtX+gnLFlHMQdeT0W19XFv/0a8AQw+zogqdXr+0lDCZ34Kn0sU31kRB3QqTJBSC+CTFVFt2LvfsM3qe+caxNOUG8WJq3WstVxhn4obMYVnE5+DgFV1SHUfpHvEncrfirXZEuDIOv/U0sSbFsUY/8VdopoNVoG1+YIYpoKFItH52LR4WOfjrxr5jrHXMvky8X7/jJG6wG6G83wOPWcGBHBmnCiIEe2tmrinY51arKHSUbQyL29swUp5JGo1NfR/PXpqUtIv4gFFd52SPW5DLAkYs6eFl8Z2yiaVVEsgRczw8FWMQkGewilZI96TmhpQkpnvewJVwWbD1KXkFBbJYt0SmnROz4zwv8x7JRW7PceOS8nCwdMoPQaXiAFKYEp1L6G84oywUpbGGJuJvidaJlemk5NTERc1kbPAG/vuVX2z10sf2qeqtp2mdmZWszDQOOnqPVQiLGcxWQadxbB/JvRlpogIJWNMGvCH5cZkIxkJ5e8ezq/dXbv/VMGMCz5Gtdv7cG2RvGUzH67jhy4AfXCziJYZ54xwcXT/axU6C/2s7pnsX2IryufDlfZoITH0lG7l2t5si95pGcuFL9qQ9yPTs8y8EWWBrIMIwIS7c/jLsGyKUI2TsszdNe38qqck5L5jtjSgwkAo7dMvmRE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
